Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,7 +22,8 @@ variables:
     - cd ${SOURCE_WORKSPACE}
     - |
       if [[ -f $SOURCE_WORKSPACE/poky/meta/classes/create-spdx.bbclass ]]; then 
-        echo "=============== Disabling SBOM ======================="
+        echo "===============  ======================="
+        HandleLog DASH "Disabling SBOM" ${DEBUG_LOG_FILE}
         cat $SOURCE_WORKSPACE/poky/meta/classes/create-spdx.bbclass
         echo "======================================================"
         sed -i 's|^inherit create-spdx-2.2|# inherit create-spdx-2.2|' $SOURCE_WORKSPACE/poky/meta/classes/create-spdx.bbclass
@@ -35,11 +36,13 @@ variables:
     # AWS S3 BASED SSTATE CACHE SETUP
     ###########################################################################
     - |
+      HandleLog DASH "S3 BUCKET CACHE FOLDER CREATE" ${DEBUG_LOG_FILE}
       aws s3api put-object --bucket ${OT_SSTATE_BUCKET} --key onetree/EGS/sstate-cache/.keep
       aws s3api put-object --bucket ${OT_SSTATE_BUCKET} --key onetree/BHS/sstate-cache/.keep
       aws s3api put-object --bucket ${OT_SSTATE_BUCKET} --key onetree/AMD_TRUIN/sstate-cache/.keep
       aws s3api put-object --bucket ${OT_SSTATE_BUCKET} --key onetree/AMPERE_MITCHELL/sstate-cache/.keep
       aws s3api put-object --bucket ${OT_SSTATE_BUCKET} --key onetree/NVIDIA_GRACEHOPPER/sstate-cache/.keep
+      HandleLog SUCCESS "FOLDERS CREATED IN S3 Bukcet" ${DEBUG_LOG_FILE}
     - | 
       if [[ ${config^^} =~ "ARCHERCITY" || ${config^^} =~ "AST2600" ]]; then 
         base_cache="EGS"
@@ -59,19 +62,19 @@ variables:
     #  DOWNLOADING SSTATE CACHE FROM AWS S3 BUCKET
     ###########################################################################
     - |
-      echo "Base cahe $base_cache"
-      echo "Bucket name $OT_SSTATE_BUCKET"
+      HandleLog INFO "BASE CACHE SET TO $base_cache" ${DEBUG_LOG_FILE}
+      HandleLog INFO "Bucket name $OT_SSTATE_BUCKET" ${DEBUG_LOG_FILE}
       if [[ ${CI_RUNNER_DESCRIPTION,,} =~ "aws" && ! "$mr_labels" =~ "OT_ENABLE_COVERITY" ]]; 
       then 
         sync_start_time=$(date +%s)
-        # aws s3 sync --sse=aws:kms --quiet s3://${OT_SSTATE_BUCKET}/onetree/$base_cache $HOME/cache/onetree/$base_cache
+        aws s3 sync --sse=aws:kms --quiet s3://${OT_SSTATE_BUCKET}/onetree/$base_cache $HOME/cache/onetree/$base_cache
         sync_end_time=$(date +%s)
-        echo "AWS AUTO SCALE Runner, Cache Sync Time from S3: $(($sync_end_time-$sync_start_time)) secs"
+        HandleLog SUCCESS "Cache Download Time from S3- $(($sync_end_time-$sync_start_time)) secs" ${DEBUG_LOG_FILE}
       fi
     - |
       mkdir -p $HOME/cache/onetree/$base_cache/downloads
       if [ -d "$HOME/cache/onetree/$base_cache/sstate-cache" ]; then
-        echo "Cache folders exist."
+        HandleLog INFO "Cache folders exist in local !" ${DEBUG_LOG_FILE}
       else
         mkdir -p $HOME/cache/onetree/$base_cache/sstate-cache
       fi
@@ -79,6 +82,7 @@ variables:
     ###########################################################################
     #  DOWNLOADED CACHE SIZE CHECKING AND ENABLING SSTATE
     ###########################################################################
+    - HandleLog DASH "SSTATE CACHE FOLDER SIZE" ${BUILD_LOG_FILE}
     - ls -lat $HOME/cache/onetree/$base_cache
     - du -h -d 2 $HOME/cache/onetree
     - du -sh $HOME/cache/onetree/$base_cache/sstate-cache
@@ -86,7 +90,9 @@ variables:
     - |
       if [[ ! "$mr_labels" =~ "OT_ENABLE_COVERITY" ]]; then
         echo "SSTATE_DIR = \"$HOME/cache/onetree/$base_cache/sstate-cache\"" >> $TEMPLATECONF/local.conf.sample
+        HandleLog SUCCESS "SSTATE_DIR $HOME/cache/onetree/$base_cache/sstate-cache ADDED !!" ${BUILD_LOG_FILE}
       fi
+    - HandleLog DASH "DONE" ${BUILD_LOG_FILE}
     
     ###########################################################################
     # CLEARNING SSTATE CACHE FOR JVIEWER
@@ -117,12 +123,11 @@ variables:
     # TEMPLATE ENV
     ###########################################################################
     - echo $(pwd)
-    - echo -e "==> Initiating template ${!template}\n"  | tee -a ${INFO_AND_LOG}/Build_log.log
     # - TEMPLATECONF=$TEMPLATECONF . openbmc-env
     - cd $SOURCE_WORKSPACE
     - ls -la
     - . ./openbmc-env
-    - echo -e "==> Completed running env script\n"  | tee -a ${INFO_AND_LOG}/Build_log.log
+    - HandleLog SUCCESS "ENV Script Ran !!" ${BUILD_LOG_FILE}
 
     ###########################################################################
     # POST ENV OPTIONS
@@ -166,14 +171,14 @@ variables:
     # RUNNING DO FETCH ALONE
     ###########################################################################
     
-    # - echo -e "==========> Started do fetch <==============\n"  | tee -a ${INFO_AND_LOG}/Build_log.log
+    # - echo -e "==========> Started do fetch <==============\n"  | tee -a ${BUILD_LOG_FILE}
     # - bitbake -D --runonly do_fetch $executer
     
     ###########################################################################
     # BITBAKE BUILD WITH/WITHOUT COVERITY
     ###########################################################################
     - set +e
-    - echo -e "==========> Started bitbake build <==============\n"  | tee -a ${INFO_AND_LOG}/Build_log.log
+    - HandleLog DASH "BITBAKE BUILD INITIALIZING" ${BUILD_LOG_FILE}
     - first_build_start_time=$(date +%s)
     - |
       findstr="Tasks Summary: Attempted [0-9]+ tasks of which [0-9]+ didn't need to be rerun and all succeeded."
@@ -185,8 +190,8 @@ variables:
         $HOME/coverity/bin/cov-configure --compiler arm-openbmc-linux-gnueabi-gcc --comptype gcc --template
         export CC=/usr/bin/gcc
         $HOME/coverity/bin/cov-configure --compiler /usr/bin/gcc
-        BB_NUMBER_THREADS=4 $HOME/coverity/bin/cov-build --dir $HOME/coverity_report bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log
-        if grep -qE "$findstr" "${INFO_AND_LOG}/Build_log.log";
+        BB_NUMBER_THREADS=4 $HOME/coverity/bin/cov-build --dir $HOME/coverity_report bitbake $executer | tee -a ${BUILD_LOG_FILE}
+        if grep -qE "$findstr" "${BUILD_LOG_FILE}";
         then
           $HOME/coverity/bin/cov-manage-emit --dir $HOME/coverity_report list | tee -a Included_list
           $HOME/coverity/bin/cov-analyze --dir $HOME/coverity_report --enable-constraint-fpp -all
@@ -201,10 +206,12 @@ variables:
           curl -F 'coverity_data=@coverity.zip' "https://devnet.ami.com/sast-bot/api/v1/coverity_ot_reports?pid=$CI_PROJECT_ID&job_url=$CI_JOB_URL&job_stage=$CI_JOB_STAGE&prj=${config}&mr_id=$MR_ID"
         fi
       else
-        BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log
+        HandleLog INFO "BITBAKE BUILD STARTED...." ${BUILD_LOG_FILE}
+        BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${BUILD_LOG_FILE}
+        HandleLog INFO "BITBAKE BUILD FINISHED" ${BUILD_LOG_FILE}
       fi
     - first_build_end_time=$(date +%s)
-    - echo "===> First build time $(($first_build_end_time-$first_build_start_time)) secs <==="
+    - HandleLog INFO "BUILD TIME TAKEN $(($first_build_end_time-$first_build_start_time)) secs" ${BUILD_LOG_FILE}
     - set -e
 
     ###########################################################################
@@ -213,31 +220,31 @@ variables:
 
     
     # - |
-    #   if ! grep -qE "$findstr" "${INFO_AND_LOG}/Build_log.log";
+    #   if ! grep -qE "$findstr" "${BUILD_LOG_FILE}";
     #   then 
-    #     echo -e "\n\n==========> Retrying bitbake build <==============\n"  | tee -a ${INFO_AND_LOG}/Build_log.log;
+    #     echo -e "\n\n==========> Retrying bitbake build <==============\n"  | tee -a ${BUILD_LOG_FILE};
     #     retry_build_start_time=$(date +%s)
     #     if [[ ! "$mr_labels" =~ "OT_ENABLE_COVERITY" ]];then
     #       set +e
-    #       BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log
+    #       BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${BUILD_LOG_FILE}
     #       set -e
     #       retry_build_end_time=$(date +%s)
     #       echo "===> Retry 1 build time $(($retry_build_end_time-$retry_build_start_time)) secs <==="
           
-    #       # if ! grep -qE "$findstr" "${INFO_AND_LOG}/Build_log.log";then 
-    #       #     echo -e "\n\n==========> Second time Retrying bitbake build <==============\n"  | tee -a ${INFO_AND_LOG}/Build_log.log;
+    #       # if ! grep -qE "$findstr" "${BUILD_LOG_FILE}";then 
+    #       #     echo -e "\n\n==========> Second time Retrying bitbake build <==============\n"  | tee -a ${BUILD_LOG_FILE};
     #       #     retry_build_start_time=$(date +%s)
     #       #     python3 -c "import time; import random; slp=random.randint(10, 30); print('sleeping:', slp); time.sleep(random.randint(10, 20))"
     #       #     set +e
-    #       #     BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log;
+    #       #     BB_NUMBER_THREADS=8 bitbake $executer | tee -a ${BUILD_LOG_FILE};
     #       #     set -e
     #       #     retry_build_end_time=$(date +%s)
     #       #     echo "===> Retry 2 build time $(($retry_build_end_time-$retry_build_start_time)) secs <==="
-    #       #     # bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log
+    #       #     # bitbake $executer | tee -a ${BUILD_LOG_FILE}
     #       # fi
 
     #     else
-    #       BB_NUMBER_THREADS=4 $HOME/coverity/bin/cov-build --dir $HOME/coverity_report bitbake $executer | tee -a ${INFO_AND_LOG}/Build_log.log
+    #       BB_NUMBER_THREADS=4 $HOME/coverity/bin/cov-build --dir $HOME/coverity_report bitbake $executer | tee -a ${BUILD_LOG_FILE}
     #       retry_build_end_time=$(date +%s)
     #       echo "===> Retry 1 build time $(($retry_build_end_time-$retry_build_start_time)) secs <==="
     #       $HOME/coverity/bin/cov-manage-emit --dir $HOME/coverity_report list | tee -a Included_list
@@ -268,16 +275,15 @@ variables:
         # du -h --all $HOME/cache/onetree/$base_cache/sstate-cache
         aws s3 sync --quiet --sse=aws:kms $HOME/cache/onetree/$base_cache/sstate-cache s3://${OT_SSTATE_BUCKET}/onetree/$base_cache/sstate-cache 
         sync_end_time=$(date +%s)
-        echo "Cache sync finished .."
-        echo "AWS AUTO SCALE Runner, Cache Sync Time from S3: $(($sync_end_time-$sync_start_time)) secs"
+        HandleLog INFO "CACHE UPLOADED TIME $(($sync_end_time-$sync_start_time)) secs" ${BUILD_LOG_FILE}
       fi
 
     ###########################################################################
     # CAPUTURING LOG FILES TO ARTIFACTS
     ###########################################################################
 
-    #- items=$(cat ${INFO_AND_LOG}/Build_log.log | grep "ERROR: Logfile of failure stored in:" | awk -F"stored in:" '{print $NF}')
-    #- items=$(awk -F"stored in: " '/ERROR: Logfile of failure stored in:/ {print $NF}' ${INFO_AND_LOG}/Build_log.log)
+    #- items=$(cat ${BUILD_LOG_FILE} | grep "ERROR: Logfile of failure stored in:" | awk -F"stored in:" '{print $NF}')
+    #- items=$(awk -F"stored in: " '/ERROR: Logfile of failure stored in:/ {print $NF}' ${BUILD_LOG_FILE})
     #- echo "==> Error log files"
     #- echo $items
     #- for logfile in ${items[@]}; do echo "==> Log file path $logfile";cp -r $logfile ${INFO_AND_LOG}; done
@@ -288,11 +294,14 @@ variables:
     # COPYING IMAGES TO ARTIFACTS
     ###########################################################################
     - |
+      HandleLog DASH " ## BUILD RESULT ## " ${BUILD_LOG_FILE}
       findstr="Tasks Summary: Attempted [0-9]+ tasks of which [0-9]+ didn't need to be rerun and all succeeded."
-      if ! grep -qE "$findstr" ${INFO_AND_LOG}/Build_log.log; then
-       echo "Build Failed"
+      if ! grep -qE "$findstr" ${BUILD_LOG_FILE}; then
+       HandleLog ERROR "BUILD FAILED !!!!" ${BUILD_LOG_FILE}
        exit 1
       else
+        HandleLog SUCCESS "BUILD SUCCESS !!!!" ${BUILD_LOG_FILE}
+        HandleLog DASH " ## DONE ## " ${BUILD_LOG_FILE}
         echo "====> Listing image folder"
         ls -la $SOURCE_WORKSPACE/build/tmp/deploy/images
         echo "=====> nested folders"
@@ -300,46 +309,47 @@ variables:
         ls -la $folder_path_
         echo "====> Calculating image folder size"
         du -h -d 5 $SOURCE_WORKSPACE/build/tmp/deploy/images
-        # echo "====> Copying images to artifacts"
-        # cp -r $(pwd)/tmp/deploy/images $OUTPUT
-        
-
-        # Copy U-BOOT file
-        UbootFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname u-boot.bin)
-        if [ -f ${UbootFile} ] && [ "${UbootFile}" != "" ]; then cp ${UbootFile} ${OUTPUT}/$(printf "${config}_${version}_u-boot".bin); fi
-
-        # Copy Kernel/FitImage file
-        FitImage=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname fitImage)
-        if [ -f ${FitImage} ] && [ "${FitImage}" != "" ]; then cp ${FitImage} ${OUTPUT}/$(printf "${config}_${version}_fitimage".bin); fi
-
-        # Copy DTB file
-        AsppedBmcIntelAst2600DtbFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname aspeed-bmc-intel-ast2600.dtb)
-        if [ -f ${AsppedBmcIntelAst2600DtbFile} ] && [ "${AsppedBmcIntelAst2600DtbFile}" != "" ]; then cp ${AsppedBmcIntelAst2600DtbFile} ${OUTPUT}/$(printf "${config}_${version}".dtb); fi
-
-        # Copy OS/Rootfs image file
-        RootfsFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname fitImage-rootfs-intel-ast2600.bin)
-        if [ -f ${RootfsFile} ] && [ "${RootfsFile}" != "" ]; then cp ${RootfsFile} ${OUTPUT}/$(printf "${config}_${version}_rootfs".bin); fi
-
-        # Copy tar (image-update, full) files
-        TarFiles=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* | grep intel-platforms-image-update-full-intel*)
-        if [ -f ${TarFiles} ] && [ "${TarFiles}" != "" ]; then cp ${TarFiles} ${OUTPUT}/$(printf "${config}_${version}_intel-platforms-image-update-full-intel".tar); fi
-        
-        # Copy MTD file
-        MtdFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname image-mtd)
-        if [ -f ${MtdFile} ] && [ "${MtdFile}" != "" ]; then cp ${MtdFile} ${OUTPUT}/$(printf "${config}_${version}".mtd); fi
-        
-        # Copy PFR file
-        PFRFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname pfr_images)
-        if [ -f ${PFRFile} ] && [ "${PFRFile}" != "" ]; then cp ${PFRFile} ${OUTPUT}/$(printf "${config}_${version}_pfr".bin); fi
-
-        # Copy JViewer.jar
-        JARFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname utilities)
-        if [ -d ${JARFile} ] && [ "${JARFile}" != "" ]; then cp -r ${JARFile} ${OUTPUT}/; fi
-
-
-        echo "Build Successfully Completed !!"
 
       fi
+    - |
+      HandleLog DASH "COPYING IMAGES TO ARTIFACTS !!" ${BUILD_LOG_FILE}
+      # Copy U-BOOT file
+      UbootFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname u-boot.bin)
+      if [ -f ${UbootFile} ] && [ "${UbootFile}" != "" ]; then cp ${UbootFile} ${OUTPUT}/$(printf "${config}_${version}_u-boot".bin); fi
+
+      # Copy Kernel/FitImage file
+      FitImage=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname fitImage)
+      if [ -f ${FitImage} ] && [ "${FitImage}" != "" ]; then cp ${FitImage} ${OUTPUT}/$(printf "${config}_${version}_fitimage".bin); fi
+
+      # Copy DTB file
+      AsppedBmcIntelAst2600DtbFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname aspeed-bmc-intel-ast2600.dtb)
+      if [ -f ${AsppedBmcIntelAst2600DtbFile} ] && [ "${AsppedBmcIntelAst2600DtbFile}" != "" ]; then cp ${AsppedBmcIntelAst2600DtbFile} ${OUTPUT}/$(printf "${config}_${version}".dtb); fi
+
+      # Copy OS/Rootfs image file
+      RootfsFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname fitImage-rootfs-intel-ast2600.bin)
+      if [ -f ${RootfsFile} ] && [ "${RootfsFile}" != "" ]; then cp ${RootfsFile} ${OUTPUT}/$(printf "${config}_${version}_rootfs".bin); fi
+
+      # Copy tar (image-update, full) files
+      TarFiles=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* | grep intel-platforms-image-update-full-intel*)
+      if [ -f ${TarFiles} ] && [ "${TarFiles}" != "" ]; then cp ${TarFiles} ${OUTPUT}/$(printf "${config}_${version}_intel-platforms-image-update-full-intel".tar); fi
+      
+      # Copy MTD file
+      MtdFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname image-mtd)
+      if [ -f ${MtdFile} ] && [ "${MtdFile}" != "" ]; then cp ${MtdFile} ${OUTPUT}/$(printf "${config}_${version}".mtd); fi
+      
+      # Copy PFR file
+      PFRFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname pfr_images)
+      if [ -f ${PFRFile} ] && [ "${PFRFile}" != "" ]; then cp ${PFRFile} ${OUTPUT}/$(printf "${config}_${version}_pfr".bin); fi
+
+      # Copy JViewer.jar
+      JARFile=$(find $SOURCE_WORKSPACE/build/tmp/deploy/images/* -iname utilities)
+      if [ -d ${JARFile} ] && [ "${JARFile}" != "" ]; then cp -r ${JARFile} ${OUTPUT}/; fi
+
+      HandleLog DASH " ## COPIED !! ## " ${BUILD_LOG_FILE}
+
+    - echo "Build Successfully Completed !!"
+
+
   tags:
     - $runner_tag
   artifacts:
